config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :events

  resources :pessoa_juridicas

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/pessoa_juridica.rb
class PessoaJuridica < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :info)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pessoa_juridicas_controller.rb
class PessoaJuridicasController < ApplicationController
  before_action :set_pessoa_juridica, only: [:show, :edit, :update, :destroy]

  # GET /pessoa_juridicas
  # GET /pessoa_juridicas.json
  def index
    @pessoa_juridicas = PessoaJuridica.all
  end

  # GET /pessoa_juridicas/1
  # GET /pessoa_juridicas/1.json
  def show
  end

  # GET /pessoa_juridicas/new
  def new
    @pessoa_juridica = PessoaJuridica.new
  end

  # GET /pessoa_juridicas/1/edit
  def edit
  end

  # POST /pessoa_juridicas
  # POST /pessoa_juridicas.json
  def create
    @pessoa_juridica = PessoaJuridica.new(pessoa_juridica_params)

    respond_to do |format|
      if @pessoa_juridica.save
        format.html { redirect_to @pessoa_juridica, notice: 'Pessoa juridica was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa_juridica }
      else
        format.html { render :new }
        format.json { render json: @pessoa_juridica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoa_juridicas/1
  # PATCH/PUT /pessoa_juridicas/1.json
  def update
    respond_to do |format|
      if @pessoa_juridica.update(pessoa_juridica_params)
        format.html { redirect_to @pessoa_juridica, notice: 'Pessoa juridica was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa_juridica }
      else
        format.html { render :edit }
        format.json { render json: @pessoa_juridica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoa_juridicas/1
  # DELETE /pessoa_juridicas/1.json
  def destroy
    @pessoa_juridica.destroy
    respond_to do |format|
      format.html { redirect_to pessoa_juridicas_url, notice: 'Pessoa juridica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa_juridica
      @pessoa_juridica = PessoaJuridica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_juridica_params
      params.require(:pessoa_juridica).permit(:nome, :nome_fantasia, :nire, :data_nire, :incricao_estadual, :data_inscricao_estadual, :senha_estadual, :inscricao_municipa, :data_inscricao_municipal, :alvara, :data_alvara)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pessoa_juridicas_helper.rb
module PessoaJuridicasHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.info %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @event.info %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gescomp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gescomp" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pessoa_juridicas/_form.html.erb
<%= form_for(@pessoa_juridica) do |f| %>
  <% if @pessoa_juridica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa_juridica.errors.count, "error") %> prohibited this pessoa_juridica from being saved:</h2>

      <ul>
      <% @pessoa_juridica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :nome_fantasia %><br>
    <%= f.text_field :nome_fantasia %>
  </div>
  <div class="field">
    <%= f.label :nire %><br>
    <%= f.text_field :nire %>
  </div>
  <div class="field">
    <%= f.label :data_nire %><br>
    <%= f.date_select :data_nire %>
  </div>
  <div class="field">
    <%= f.label :incricao_estadual %><br>
    <%= f.text_field :incricao_estadual %>
  </div>
  <div class="field">
    <%= f.label :data_inscricao_estadual %><br>
    <%= f.date_select :data_inscricao_estadual %>
  </div>
  <div class="field">
    <%= f.label :senha_estadual %><br>
    <%= f.text_field :senha_estadual %>
  </div>
  <div class="field">
    <%= f.label :inscricao_municipa %><br>
    <%= f.text_field :inscricao_municipa %>
  </div>
  <div class="field">
    <%= f.label :data_inscricao_municipal %><br>
    <%= f.date_select :data_inscricao_municipal %>
  </div>
  <div class="field">
    <%= f.label :alvara %><br>
    <%= f.text_field :alvara %>
  </div>
  <div class="field">
    <%= f.label :data_alvara %><br>
    <%= f.date_select :data_alvara %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoa_juridicas/edit.html.erb
<h1>Editing Pessoa Juridica</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa_juridica %> |
<%= link_to 'Back', pessoa_juridicas_path %>

app/views/pessoa_juridicas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pessoa Juridicas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nome fantasia</th>
      <th>Nire</th>
      <th>Data nire</th>
      <th>Incricao estadual</th>
      <th>Data inscricao estadual</th>
      <th>Senha estadual</th>
      <th>Inscricao municipa</th>
      <th>Data inscricao municipal</th>
      <th>Alvara</th>
      <th>Data alvara</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoa_juridicas.each do |pessoa_juridica| %>
      <tr>
        <td><%= pessoa_juridica.nome %></td>
        <td><%= pessoa_juridica.nome_fantasia %></td>
        <td><%= pessoa_juridica.nire %></td>
        <td><%= pessoa_juridica.data_nire %></td>
        <td><%= pessoa_juridica.incricao_estadual %></td>
        <td><%= pessoa_juridica.data_inscricao_estadual %></td>
        <td><%= pessoa_juridica.senha_estadual %></td>
        <td><%= pessoa_juridica.inscricao_municipa %></td>
        <td><%= pessoa_juridica.data_inscricao_municipal %></td>
        <td><%= pessoa_juridica.alvara %></td>
        <td><%= pessoa_juridica.data_alvara %></td>
        <td><%= link_to 'Show', pessoa_juridica %></td>
        <td><%= link_to 'Edit', edit_pessoa_juridica_path(pessoa_juridica) %></td>
        <td><%= link_to 'Destroy', pessoa_juridica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa juridica', new_pessoa_juridica_path %>

app/views/pessoa_juridicas/new.html.erb
<h1>New Pessoa Juridica</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoa_juridicas_path %>

app/views/pessoa_juridicas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa_juridica.nome %>
</p>

<p>
  <strong>Nome fantasia:</strong>
  <%= @pessoa_juridica.nome_fantasia %>
</p>

<p>
  <strong>Nire:</strong>
  <%= @pessoa_juridica.nire %>
</p>

<p>
  <strong>Data nire:</strong>
  <%= @pessoa_juridica.data_nire %>
</p>

<p>
  <strong>Incricao estadual:</strong>
  <%= @pessoa_juridica.incricao_estadual %>
</p>

<p>
  <strong>Data inscricao estadual:</strong>
  <%= @pessoa_juridica.data_inscricao_estadual %>
</p>

<p>
  <strong>Senha estadual:</strong>
  <%= @pessoa_juridica.senha_estadual %>
</p>

<p>
  <strong>Inscricao municipa:</strong>
  <%= @pessoa_juridica.inscricao_municipa %>
</p>

<p>
  <strong>Data inscricao municipal:</strong>
  <%= @pessoa_juridica.data_inscricao_municipal %>
</p>

<p>
  <strong>Alvara:</strong>
  <%= @pessoa_juridica.alvara %>
</p>

<p>
  <strong>Data alvara:</strong>
  <%= @pessoa_juridica.data_alvara %>
</p>

<%= link_to 'Edit', edit_pessoa_juridica_path(@pessoa_juridica) %> |
<%= link_to 'Back', pessoa_juridicas_path %>